# --- General Settings ---
set -g mouse on
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# --- 1. Load Matugen Colors ---
source-file ~/.config/tmux/generated.conf

# --- 2. Force Transparency & Map Matugen to Catppuccin ---
# Overwrite the Matugen bg variable to be transparent
set -gq @thm_bg "default"
set -g status-bg default
set -g status-style "bg=default"

# Map Matugen colors to the Dreams of Code / Catppuccin variables
set -g @catppuccin_flavour 'mocha'
# --- Plugins ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'

# --- Initialize TPM (Keep this at the very bottom) ---
run '~/.config/tmux/plugins/tpm/tpm'
